/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AddIncomeRouteImport } from './routes/add.income'
import { Route as IncomesIncomeIdEditRouteImport } from './routes/incomes.$incomeId.edit'
import { Route as ExpensesExpenseIdEditRouteImport } from './routes/expenses.$expenseId.edit'

const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIncomeRoute = AddIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AddRoute,
} as any)
const IncomesIncomeIdEditRoute = IncomesIncomeIdEditRouteImport.update({
  id: '/incomes/$incomeId/edit',
  path: '/incomes/$incomeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdEditRoute = ExpensesExpenseIdEditRouteImport.update({
  id: '/expenses/$expenseId/edit',
  path: '/expenses/$expenseId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/add/income': typeof AddIncomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/add/income': typeof AddIncomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/add/income': typeof AddIncomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/add/income'
    | '/auth/callback'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/add/income'
    | '/auth/callback'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/add/income'
    | '/auth/callback'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExpensesExpenseIdEditRoute: typeof ExpensesExpenseIdEditRoute
  IncomesIncomeIdEditRoute: typeof IncomesIncomeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/income': {
      id: '/add/income'
      path: '/income'
      fullPath: '/add/income'
      preLoaderRoute: typeof AddIncomeRouteImport
      parentRoute: typeof AddRoute
    }
    '/incomes/$incomeId/edit': {
      id: '/incomes/$incomeId/edit'
      path: '/incomes/$incomeId/edit'
      fullPath: '/incomes/$incomeId/edit'
      preLoaderRoute: typeof IncomesIncomeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId/edit': {
      id: '/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof ExpensesExpenseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AddRouteChildren {
  AddIncomeRoute: typeof AddIncomeRoute
}

const AddRouteChildren: AddRouteChildren = {
  AddIncomeRoute: AddIncomeRoute,
}

const AddRouteWithChildren = AddRoute._addFileChildren(AddRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ExpensesExpenseIdEditRoute: ExpensesExpenseIdEditRoute,
  IncomesIncomeIdEditRoute: IncomesIncomeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
