/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackAuthRouteImport } from './routes/callback.auth'
import { Route as AddIncomeRouteImport } from './routes/add.income'
import { Route as IncomesIncomeIdEditRouteImport } from './routes/incomes.$incomeId.edit'
import { Route as ExpensesExpenseIdEditRouteImport } from './routes/expenses.$expenseId.edit'
import { Route as BoardsBoardIdEditRouteImport } from './routes/boards.$boardId.edit'

const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackAuthRoute = CallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIncomeRoute = AddIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AddRoute,
} as any)
const IncomesIncomeIdEditRoute = IncomesIncomeIdEditRouteImport.update({
  id: '/incomes/$incomeId/edit',
  path: '/incomes/$incomeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdEditRoute = ExpensesExpenseIdEditRouteImport.update({
  id: '/expenses/$expenseId/edit',
  path: '/expenses/$expenseId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdEditRoute = BoardsBoardIdEditRouteImport.update({
  id: '/boards/$boardId/edit',
  path: '/boards/$boardId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/invite': typeof InviteRoute
  '/add/income': typeof AddIncomeRoute
  '/callback/auth': typeof CallbackAuthRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/invite': typeof InviteRoute
  '/add/income': typeof AddIncomeRoute
  '/callback/auth': typeof CallbackAuthRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRouteWithChildren
  '/invite': typeof InviteRoute
  '/add/income': typeof AddIncomeRoute
  '/callback/auth': typeof CallbackAuthRoute
  '/boards/$boardId/edit': typeof BoardsBoardIdEditRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
  '/incomes/$incomeId/edit': typeof IncomesIncomeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/invite'
    | '/add/income'
    | '/callback/auth'
    | '/boards/$boardId/edit'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/invite'
    | '/add/income'
    | '/callback/auth'
    | '/boards/$boardId/edit'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/invite'
    | '/add/income'
    | '/callback/auth'
    | '/boards/$boardId/edit'
    | '/expenses/$expenseId/edit'
    | '/incomes/$incomeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRouteWithChildren
  InviteRoute: typeof InviteRoute
  CallbackAuthRoute: typeof CallbackAuthRoute
  BoardsBoardIdEditRoute: typeof BoardsBoardIdEditRoute
  ExpensesExpenseIdEditRoute: typeof ExpensesExpenseIdEditRoute
  IncomesIncomeIdEditRoute: typeof IncomesIncomeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/auth': {
      id: '/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof CallbackAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/income': {
      id: '/add/income'
      path: '/income'
      fullPath: '/add/income'
      preLoaderRoute: typeof AddIncomeRouteImport
      parentRoute: typeof AddRoute
    }
    '/incomes/$incomeId/edit': {
      id: '/incomes/$incomeId/edit'
      path: '/incomes/$incomeId/edit'
      fullPath: '/incomes/$incomeId/edit'
      preLoaderRoute: typeof IncomesIncomeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId/edit': {
      id: '/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof ExpensesExpenseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/edit': {
      id: '/boards/$boardId/edit'
      path: '/boards/$boardId/edit'
      fullPath: '/boards/$boardId/edit'
      preLoaderRoute: typeof BoardsBoardIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AddRouteChildren {
  AddIncomeRoute: typeof AddIncomeRoute
}

const AddRouteChildren: AddRouteChildren = {
  AddIncomeRoute: AddIncomeRoute,
}

const AddRouteWithChildren = AddRoute._addFileChildren(AddRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRouteWithChildren,
  InviteRoute: InviteRoute,
  CallbackAuthRoute: CallbackAuthRoute,
  BoardsBoardIdEditRoute: BoardsBoardIdEditRoute,
  ExpensesExpenseIdEditRoute: ExpensesExpenseIdEditRoute,
  IncomesIncomeIdEditRoute: IncomesIncomeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
