/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ExpensesExpenseIdEditRouteImport } from './routes/expenses.$expenseId.edit'

const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdEditRoute = ExpensesExpenseIdEditRouteImport.update({
  id: '/expenses/$expenseId/edit',
  path: '/expenses/$expenseId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/expenses/$expenseId/edit': typeof ExpensesExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/auth/callback' | '/expenses/$expenseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/auth/callback' | '/expenses/$expenseId/edit'
  id: '__root__' | '/' | '/add' | '/auth/callback' | '/expenses/$expenseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExpensesExpenseIdEditRoute: typeof ExpensesExpenseIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId/edit': {
      id: '/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof ExpensesExpenseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ExpensesExpenseIdEditRoute: ExpensesExpenseIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
