/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "auth": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "authAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "authTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "webapp": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}