INSERT INTO "categories" ("name", "emoji", "type") VALUES
('Supermercados', '🛒', 'expense'),
('Restaurantes', '🍽️', 'expense'),
('Cafeterías/Snacks', '☕', 'expense'),
('Delivery', '🛵', 'expense'),
('Comida rápida', '🍟', 'expense'),
('Bebidas/Alcohol', '🍺', 'expense'),
('Gasolina', '⛽', 'expense'),
('Mantenimiento Vehículo', '🔧', 'expense'),
('Uber/Didi', '🚕', 'expense'),
('Transporte público', '🚌', 'expense'),
('Peajes', '🛣️', 'expense'),
('Estacionamiento', '🅿️', 'expense'),
('Alquiler/Hipoteca', '🏡', 'expense'),
('Luz', '💡', 'expense'),
('Agua', '🚿', 'expense'),
('Gas', '🔥', 'expense'),
('Internet/Telefonía', '🌐', 'expense'),
('Seguridad/Admin', '🛡️', 'expense'),
('Muebles/Jardín', '🪑', 'expense'),
('Farmacia', '💊', 'expense'),
('Consultas médicas', '🩺', 'expense'),
('Dentista', '🦷', 'expense'),
('Gim./Deportes', '🏋️', 'expense'),
('Cuidado personal', '✂️', 'expense'),
('Seguro salud', '❤️', 'expense'),
('Cine/Eventos', '🎟️', 'expense'),
('Streaming', '📺', 'expense'),
('Bares/Discotecas', '🍹', 'expense'),
('Hobbies/Juegos', '🎮', 'expense'),
('Suscripciones', '💳', 'expense'),
('Ropa/Calzado', '👕', 'expense'),
('Electrónica', '📱', 'expense'),
('Regalos', '🎁', 'expense'),
('Mascotas', '🐶', 'expense'),
('Cursos', '📚', 'expense'),
('Libros', '📖', 'expense'),
('Viajes', '✈️', 'expense'),
('Impuestos', '🧾', 'expense'),
('Otros', '📦', 'expense'),
('Sueldo', '💼', 'income'),
('Transferencias', '🔁', 'income'),
('Reembolsos', '💸', 'income'),
('Intereses', '📈', 'income'),
('Ventas', '🛒', 'income')
ON CONFLICT DO NOTHING;
